name: amaxdart
description: Armonia Meta Chain RPC API client in Dart language
version: 0.4.8+20220331
homepage: https://github.com/niclas9/amaxdart
publish_to: https://pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.0
  json_annotation: ^4.0.1
  pointycastle: ^3.3.5
  amaxdart_ecc: ^0.4.4

dev_dependencies:
  test: ^1.19.2
  build_runner: ^2.1.4
  json_serializable: ^6.0.1
